package com.care.mybatis.dao;

import com.care.mybatis.bean.Auto;
import com.care.mybatis.bean.AutoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AutoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int countByExample(AutoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int deleteByExample(AutoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int insert(Auto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int insertSelective(Auto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	List<Auto> selectByExample(AutoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	Auto selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Auto record, @Param("example") AutoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByExample(@Param("record") Auto record, @Param("example") AutoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByPrimaryKeySelective(Auto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByPrimaryKey(Auto record);
}