package com.care.mybatis.dao;

import com.care.mybatis.bean.AutoFault;
import com.care.mybatis.bean.AutoFaultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AutoFaultMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int countByExample(AutoFaultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int deleteByExample(AutoFaultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int insert(AutoFault record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int insertSelective(AutoFault record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	List<AutoFault> selectByExample(AutoFaultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	AutoFault selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int updateByExampleSelective(@Param("record") AutoFault record,
			@Param("example") AutoFaultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int updateByExample(@Param("record") AutoFault record,
			@Param("example") AutoFaultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int updateByPrimaryKeySelective(AutoFault record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int updateByPrimaryKey(AutoFault record);
}