package com.care.mybatis.dao;

import com.care.mybatis.bean.AutoFaultType;
import com.care.mybatis.bean.AutoFaultTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AutoFaultTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault_type
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	int countByExample(AutoFaultTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault_type
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	int deleteByExample(AutoFaultTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault_type
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault_type
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	int insert(AutoFaultType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault_type
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	int insertSelective(AutoFaultType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault_type
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	List<AutoFaultType> selectByExample(AutoFaultTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault_type
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	AutoFaultType selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault_type
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	int updateByExampleSelective(@Param("record") AutoFaultType record,
			@Param("example") AutoFaultTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault_type
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	int updateByExample(@Param("record") AutoFaultType record,
			@Param("example") AutoFaultTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault_type
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	int updateByPrimaryKeySelective(AutoFaultType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_fault_type
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	int updateByPrimaryKey(AutoFaultType record);
}