package com.care.mybatis.dao;

import com.care.mybatis.bean.AutoMaintenanceAppoint;
import com.care.mybatis.bean.AutoMaintenanceAppointExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AutoMaintenanceAppointMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_maintenance_appoint
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int countByExample(AutoMaintenanceAppointExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_maintenance_appoint
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int deleteByExample(AutoMaintenanceAppointExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_maintenance_appoint
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_maintenance_appoint
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int insert(AutoMaintenanceAppoint record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_maintenance_appoint
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int insertSelective(AutoMaintenanceAppoint record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_maintenance_appoint
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	List<AutoMaintenanceAppoint> selectByExample(AutoMaintenanceAppointExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_maintenance_appoint
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	AutoMaintenanceAppoint selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_maintenance_appoint
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByExampleSelective(@Param("record") AutoMaintenanceAppoint record, @Param("example") AutoMaintenanceAppointExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_maintenance_appoint
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByExample(@Param("record") AutoMaintenanceAppoint record, @Param("example") AutoMaintenanceAppointExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_maintenance_appoint
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByPrimaryKeySelective(AutoMaintenanceAppoint record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_maintenance_appoint
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByPrimaryKey(AutoMaintenanceAppoint record);
}