package com.care.mybatis.dao;

import com.care.mybatis.bean.AutoBrand;
import com.care.mybatis.bean.AutoBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AutoBrandMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_brand
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int countByExample(AutoBrandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_brand
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int deleteByExample(AutoBrandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_brand
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_brand
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int insert(AutoBrand record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_brand
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int insertSelective(AutoBrand record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_brand
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	List<AutoBrand> selectByExample(AutoBrandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_brand
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	AutoBrand selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_brand
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByExampleSelective(@Param("record") AutoBrand record, @Param("example") AutoBrandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_brand
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByExample(@Param("record") AutoBrand record, @Param("example") AutoBrandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_brand
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByPrimaryKeySelective(AutoBrand record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_brand
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByPrimaryKey(AutoBrand record);
}