package com.care.mybatis.dao;

import com.care.mybatis.bean.AutoQuantity;
import com.care.mybatis.bean.AutoQuantityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AutoQuantityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_quantity
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	int countByExample(AutoQuantityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_quantity
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	int deleteByExample(AutoQuantityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_quantity
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_quantity
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	int insert(AutoQuantity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_quantity
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	int insertSelective(AutoQuantity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_quantity
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	List<AutoQuantity> selectByExample(AutoQuantityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_quantity
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	AutoQuantity selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_quantity
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	int updateByExampleSelective(@Param("record") AutoQuantity record,
			@Param("example") AutoQuantityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_quantity
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	int updateByExample(@Param("record") AutoQuantity record,
			@Param("example") AutoQuantityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_quantity
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	int updateByPrimaryKeySelective(AutoQuantity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_quantity
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	int updateByPrimaryKey(AutoQuantity record);
}