package com.care.mybatis.dao;

import com.care.mybatis.bean.AutoWidgetType;
import com.care.mybatis.bean.AutoWidgetTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AutoWidgetTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_widget_type
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int countByExample(AutoWidgetTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_widget_type
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int deleteByExample(AutoWidgetTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_widget_type
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_widget_type
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int insert(AutoWidgetType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_widget_type
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int insertSelective(AutoWidgetType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_widget_type
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	List<AutoWidgetType> selectByExample(AutoWidgetTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_widget_type
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	AutoWidgetType selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_widget_type
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int updateByExampleSelective(@Param("record") AutoWidgetType record,
			@Param("example") AutoWidgetTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_widget_type
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int updateByExample(@Param("record") AutoWidgetType record,
			@Param("example") AutoWidgetTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_widget_type
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int updateByPrimaryKeySelective(AutoWidgetType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auto_widget_type
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int updateByPrimaryKey(AutoWidgetType record);
}