package com.care.mybatis.dao;

import com.care.mybatis.bean.AutoVolume;
import com.care.mybatis.bean.AutoVolumeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AutoVolumeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_volume
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    int countByExample(AutoVolumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_volume
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    int deleteByExample(AutoVolumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_volume
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_volume
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    int insert(AutoVolume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_volume
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    int insertSelective(AutoVolume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_volume
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    List<AutoVolume> selectByExample(AutoVolumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_volume
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    AutoVolume selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_volume
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    int updateByExampleSelective(@Param("record") AutoVolume record, @Param("example") AutoVolumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_volume
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    int updateByExample(@Param("record") AutoVolume record, @Param("example") AutoVolumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_volume
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    int updateByPrimaryKeySelective(AutoVolume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_volume
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    int updateByPrimaryKey(AutoVolume record);
}