package com.care.mybatis.dao;

import com.care.mybatis.bean.AutoType;
import com.care.mybatis.bean.AutoTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AutoTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    int countByExample(AutoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    int deleteByExample(AutoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    int insert(AutoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    int insertSelective(AutoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    List<AutoType> selectByExample(AutoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    AutoType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    int updateByExampleSelective(@Param("record") AutoType record, @Param("example") AutoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    int updateByExample(@Param("record") AutoType record, @Param("example") AutoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    int updateByPrimaryKeySelective(AutoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    int updateByPrimaryKey(AutoType record);
}