package com.care.mybatis.dao;

import com.care.mybatis.bean.City;
import com.care.mybatis.bean.CityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	int countByExample(CityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	int deleteByExample(CityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	int insert(City record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	int insertSelective(City record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	List<City> selectByExample(CityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	City selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	int updateByExampleSelective(@Param("record") City record,
			@Param("example") CityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	int updateByExample(@Param("record") City record,
			@Param("example") CityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	int updateByPrimaryKeySelective(City record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table city
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	int updateByPrimaryKey(City record);
}