package com.care.mybatis.dao;

import com.care.mybatis.bean.UIAdver;
import com.care.mybatis.bean.UIAdverExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UIAdverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_adver
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    int countByExample(UIAdverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_adver
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    int deleteByExample(UIAdverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_adver
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_adver
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    int insert(UIAdver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_adver
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    int insertSelective(UIAdver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_adver
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    List<UIAdver> selectByExample(UIAdverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_adver
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    UIAdver selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_adver
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    int updateByExampleSelective(@Param("record") UIAdver record, @Param("example") UIAdverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_adver
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    int updateByExample(@Param("record") UIAdver record, @Param("example") UIAdverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_adver
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    int updateByPrimaryKeySelective(UIAdver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_adver
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    int updateByPrimaryKey(UIAdver record);
}