package com.care.mybatis.dao;

import com.care.mybatis.bean.UIKnowledge;
import com.care.mybatis.bean.UIKnowledgeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UIKnowledgeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_knowledge
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int countByExample(UIKnowledgeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_knowledge
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int deleteByExample(UIKnowledgeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_knowledge
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_knowledge
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int insert(UIKnowledge record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_knowledge
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int insertSelective(UIKnowledge record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_knowledge
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	List<UIKnowledge> selectByExampleWithBLOBs(UIKnowledgeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_knowledge
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	List<UIKnowledge> selectByExample(UIKnowledgeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_knowledge
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	UIKnowledge selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_knowledge
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByExampleSelective(@Param("record") UIKnowledge record, @Param("example") UIKnowledgeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_knowledge
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByExampleWithBLOBs(@Param("record") UIKnowledge record, @Param("example") UIKnowledgeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_knowledge
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByExample(@Param("record") UIKnowledge record, @Param("example") UIKnowledgeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_knowledge
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByPrimaryKeySelective(UIKnowledge record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_knowledge
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByPrimaryKeyWithBLOBs(UIKnowledge record);
}