package com.care.mybatis.dao;

import com.care.mybatis.bean.UIQuickSales;
import com.care.mybatis.bean.UIQuickSalesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UIQuickSalesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_quick_sales
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	int countByExample(UIQuickSalesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_quick_sales
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	int deleteByExample(UIQuickSalesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_quick_sales
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_quick_sales
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	int insert(UIQuickSales record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_quick_sales
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	int insertSelective(UIQuickSales record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_quick_sales
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	List<UIQuickSales> selectByExample(UIQuickSalesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_quick_sales
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	int updateByExampleSelective(@Param("record") UIQuickSales record,
			@Param("example") UIQuickSalesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_quick_sales
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	int updateByExample(@Param("record") UIQuickSales record,
			@Param("example") UIQuickSalesExample example);
}