package com.care.mybatis.dao;

import com.care.mybatis.bean.UIWebDesc;
import com.care.mybatis.bean.UIWebDescExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UIWebDescMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_web_desc
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int countByExample(UIWebDescExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_web_desc
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int deleteByExample(UIWebDescExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_web_desc
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_web_desc
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int insert(UIWebDesc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_web_desc
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int insertSelective(UIWebDesc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_web_desc
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	List<UIWebDesc> selectByExampleWithBLOBs(UIWebDescExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_web_desc
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	List<UIWebDesc> selectByExample(UIWebDescExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_web_desc
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	UIWebDesc selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_web_desc
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByExampleSelective(@Param("record") UIWebDesc record, @Param("example") UIWebDescExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_web_desc
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByExampleWithBLOBs(@Param("record") UIWebDesc record, @Param("example") UIWebDescExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_web_desc
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByExample(@Param("record") UIWebDesc record, @Param("example") UIWebDescExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_web_desc
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByPrimaryKeySelective(UIWebDesc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_web_desc
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByPrimaryKeyWithBLOBs(UIWebDesc record);
}