package com.care.mybatis.dao;

import com.care.mybatis.bean.UserStatus;
import com.care.mybatis.bean.UserStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserStatusMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_status
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int countByExample(UserStatusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_status
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int deleteByExample(UserStatusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_status
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_status
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int insert(UserStatus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_status
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int insertSelective(UserStatus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_status
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	List<UserStatus> selectByExample(UserStatusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_status
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	UserStatus selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_status
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int updateByExampleSelective(@Param("record") UserStatus record,
			@Param("example") UserStatusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_status
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int updateByExample(@Param("record") UserStatus record,
			@Param("example") UserStatusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_status
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int updateByPrimaryKeySelective(UserStatus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_status
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int updateByPrimaryKey(UserStatus record);
}