package com.care.mybatis.dao;

import com.care.mybatis.bean.widgettype_autoyear_r;
import com.care.mybatis.bean.widgettype_autoyear_rExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface widgettype_autoyear_rMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autoyear_r
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int countByExample(widgettype_autoyear_rExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autoyear_r
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int deleteByExample(widgettype_autoyear_rExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autoyear_r
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int insert(widgettype_autoyear_r record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autoyear_r
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int insertSelective(widgettype_autoyear_r record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autoyear_r
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	List<widgettype_autoyear_r> selectByExample(widgettype_autoyear_rExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autoyear_r
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByExampleSelective(@Param("record") widgettype_autoyear_r record, @Param("example") widgettype_autoyear_rExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autoyear_r
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	int updateByExample(@Param("record") widgettype_autoyear_r record, @Param("example") widgettype_autoyear_rExample example);
}