package com.care.mybatis.dao;

import com.care.mybatis.bean.widgettype_autotype_r;
import com.care.mybatis.bean.widgettype_autotype_rExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface widgettype_autotype_rMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autotype_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int countByExample(widgettype_autotype_rExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autotype_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int deleteByExample(widgettype_autotype_rExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autotype_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int insert(widgettype_autotype_r record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autotype_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int insertSelective(widgettype_autotype_r record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autotype_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	List<widgettype_autotype_r> selectByExample(
			widgettype_autotype_rExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autotype_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int updateByExampleSelective(@Param("record") widgettype_autotype_r record,
			@Param("example") widgettype_autotype_rExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autotype_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	int updateByExample(@Param("record") widgettype_autotype_r record,
			@Param("example") widgettype_autotype_rExample example);
}