package com.care.mybatis.bean;

public class AutoWidgetKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_widget.id
     *
     * @mbggenerated Sat May 17 10:40:03 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_widget.hot
     *
     * @mbggenerated Sat May 17 10:40:03 CST 2014
     */
    private Boolean hot;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_widget.id
     *
     * @return the value of auto_widget.id
     *
     * @mbggenerated Sat May 17 10:40:03 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_widget.id
     *
     * @param id the value for auto_widget.id
     *
     * @mbggenerated Sat May 17 10:40:03 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_widget.hot
     *
     * @return the value of auto_widget.hot
     *
     * @mbggenerated Sat May 17 10:40:03 CST 2014
     */
    public Boolean getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_widget.hot
     *
     * @param hot the value for auto_widget.hot
     *
     * @mbggenerated Sat May 17 10:40:03 CST 2014
     */
    public void setHot(Boolean hot) {
        this.hot = hot;
    }
}