package com.care.mybatis.bean;

public class AutoWidgetType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.name
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.year_id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private Integer yearId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.s_status
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private Integer sStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.sort
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.hot
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private Boolean hot;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.face
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private Boolean face;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.id
	 * @return  the value of auto_widget_type.id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.id
	 * @param id  the value for auto_widget_type.id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.name
	 * @return  the value of auto_widget_type.name
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.name
	 * @param name  the value for auto_widget_type.name
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.year_id
	 * @return  the value of auto_widget_type.year_id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public Integer getYearId() {
		return yearId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.year_id
	 * @param yearId  the value for auto_widget_type.year_id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setYearId(Integer yearId) {
		this.yearId = yearId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.s_status
	 * @return  the value of auto_widget_type.s_status
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public Integer getsStatus() {
		return sStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.s_status
	 * @param sStatus  the value for auto_widget_type.s_status
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setsStatus(Integer sStatus) {
		this.sStatus = sStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.sort
	 * @return  the value of auto_widget_type.sort
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.sort
	 * @param sort  the value for auto_widget_type.sort
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.hot
	 * @return  the value of auto_widget_type.hot
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public Boolean getHot() {
		return hot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.hot
	 * @param hot  the value for auto_widget_type.hot
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setHot(Boolean hot) {
		this.hot = hot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.face
	 * @return  the value of auto_widget_type.face
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public Boolean getFace() {
		return face;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.face
	 * @param face  the value for auto_widget_type.face
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setFace(Boolean face) {
		this.face = face;
	}
}