package com.care.mybatis.bean;

public class Auto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto.id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto.content
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto.img
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private String img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto.link
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private String link;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto.brand
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private Integer brand;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto.volume
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private Float volume;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto.type
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private Integer type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto.id
	 * @return  the value of auto.id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto.id
	 * @param id  the value for auto.id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto.content
	 * @return  the value of auto.content
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto.content
	 * @param content  the value for auto.content
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto.img
	 * @return  the value of auto.img
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto.img
	 * @param img  the value for auto.img
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setImg(String img) {
		this.img = img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto.link
	 * @return  the value of auto.link
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public String getLink() {
		return link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto.link
	 * @param link  the value for auto.link
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setLink(String link) {
		this.link = link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto.brand
	 * @return  the value of auto.brand
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public Integer getBrand() {
		return brand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto.brand
	 * @param brand  the value for auto.brand
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setBrand(Integer brand) {
		this.brand = brand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto.volume
	 * @return  the value of auto.volume
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public Float getVolume() {
		return volume;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto.volume
	 * @param volume  the value for auto.volume
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setVolume(Float volume) {
		this.volume = volume;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto.type
	 * @return  the value of auto.type
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto.type
	 * @param type  the value for auto.type
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setType(Integer type) {
		this.type = type;
	}
}