package com.care.mybatis.bean;

import java.util.Date;

public class AutoMaintenanceAppoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_maintenance_appoint.id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_maintenance_appoint.u_id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_maintenance_appoint.begin_time
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_maintenance_appoint.end_time
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_maintenance_appoint.auto_number
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private String autoNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_maintenance_appoint.auto_vendor
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private String autoVendor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_maintenance_appoint.phone
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_maintenance_appoint.km
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private Integer km;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_maintenance_appoint.desc
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_maintenance_appoint.id
     *
     * @return the value of auto_maintenance_appoint.id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_maintenance_appoint.id
     *
     * @param id the value for auto_maintenance_appoint.id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_maintenance_appoint.u_id
     *
     * @return the value of auto_maintenance_appoint.u_id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_maintenance_appoint.u_id
     *
     * @param uId the value for auto_maintenance_appoint.u_id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_maintenance_appoint.begin_time
     *
     * @return the value of auto_maintenance_appoint.begin_time
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_maintenance_appoint.begin_time
     *
     * @param beginTime the value for auto_maintenance_appoint.begin_time
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_maintenance_appoint.end_time
     *
     * @return the value of auto_maintenance_appoint.end_time
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_maintenance_appoint.end_time
     *
     * @param endTime the value for auto_maintenance_appoint.end_time
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_maintenance_appoint.auto_number
     *
     * @return the value of auto_maintenance_appoint.auto_number
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public String getAutoNumber() {
        return autoNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_maintenance_appoint.auto_number
     *
     * @param autoNumber the value for auto_maintenance_appoint.auto_number
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setAutoNumber(String autoNumber) {
        this.autoNumber = autoNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_maintenance_appoint.auto_vendor
     *
     * @return the value of auto_maintenance_appoint.auto_vendor
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public String getAutoVendor() {
        return autoVendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_maintenance_appoint.auto_vendor
     *
     * @param autoVendor the value for auto_maintenance_appoint.auto_vendor
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setAutoVendor(String autoVendor) {
        this.autoVendor = autoVendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_maintenance_appoint.phone
     *
     * @return the value of auto_maintenance_appoint.phone
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_maintenance_appoint.phone
     *
     * @param phone the value for auto_maintenance_appoint.phone
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_maintenance_appoint.km
     *
     * @return the value of auto_maintenance_appoint.km
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public Integer getKm() {
        return km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_maintenance_appoint.km
     *
     * @param km the value for auto_maintenance_appoint.km
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setKm(Integer km) {
        this.km = km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_maintenance_appoint.desc
     *
     * @return the value of auto_maintenance_appoint.desc
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_maintenance_appoint.desc
     *
     * @param desc the value for auto_maintenance_appoint.desc
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }
}