package com.care.mybatis.bean;

public class AutoVolume {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_volume.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_volume.name
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_volume.type_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private Integer typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_volume.year_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private Integer yearId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_volume.descr
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private String descr;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_volume.id
	 * @return  the value of auto_volume.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_volume.id
	 * @param id  the value for auto_volume.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_volume.name
	 * @return  the value of auto_volume.name
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_volume.name
	 * @param name  the value for auto_volume.name
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_volume.type_id
	 * @return  the value of auto_volume.type_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public Integer getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_volume.type_id
	 * @param typeId  the value for auto_volume.type_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_volume.year_id
	 * @return  the value of auto_volume.year_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public Integer getYearId() {
		return yearId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_volume.year_id
	 * @param yearId  the value for auto_volume.year_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setYearId(Integer yearId) {
		this.yearId = yearId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_volume.descr
	 * @return  the value of auto_volume.descr
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public String getDescr() {
		return descr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_volume.descr
	 * @param descr  the value for auto_volume.descr
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setDescr(String descr) {
		this.descr = descr;
	}
}