package com.care.mybatis.bean;

public class AutoVendor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_vendor.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_vendor.name
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_vendor.city
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_vendor.status
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_vendor.descr
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private String descr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_vendor.id
     *
     * @return the value of auto_vendor.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_vendor.id
     *
     * @param id the value for auto_vendor.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_vendor.name
     *
     * @return the value of auto_vendor.name
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_vendor.name
     *
     * @param name the value for auto_vendor.name
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_vendor.city
     *
     * @return the value of auto_vendor.city
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_vendor.city
     *
     * @param city the value for auto_vendor.city
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_vendor.status
     *
     * @return the value of auto_vendor.status
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_vendor.status
     *
     * @param status the value for auto_vendor.status
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_vendor.descr
     *
     * @return the value of auto_vendor.descr
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_vendor.descr
     *
     * @param descr the value for auto_vendor.descr
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }
}