package com.care.mybatis.bean;

public class AutoFaultType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_fault_type.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_fault_type.name
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_fault_type.is_changjian
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer isChangjian;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_fault_type.id
     *
     * @return the value of auto_fault_type.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_fault_type.id
     *
     * @param id the value for auto_fault_type.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_fault_type.name
     *
     * @return the value of auto_fault_type.name
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_fault_type.name
     *
     * @param name the value for auto_fault_type.name
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_fault_type.is_changjian
     *
     * @return the value of auto_fault_type.is_changjian
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getIsChangjian() {
        return isChangjian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_fault_type.is_changjian
     *
     * @param isChangjian the value for auto_fault_type.is_changjian
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setIsChangjian(Integer isChangjian) {
        this.isChangjian = isChangjian;
    }
}