package com.care.mybatis.bean;

public class Auto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto.id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto.content
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto.img
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto.link
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto.brand
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private Integer brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto.swept_volume
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private Float sweptVolume;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto.id
     *
     * @return the value of auto.id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto.id
     *
     * @param id the value for auto.id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto.content
     *
     * @return the value of auto.content
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto.content
     *
     * @param content the value for auto.content
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto.img
     *
     * @return the value of auto.img
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto.img
     *
     * @param img the value for auto.img
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto.link
     *
     * @return the value of auto.link
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto.link
     *
     * @param link the value for auto.link
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto.brand
     *
     * @return the value of auto.brand
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public Integer getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto.brand
     *
     * @param brand the value for auto.brand
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setBrand(Integer brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto.swept_volume
     *
     * @return the value of auto.swept_volume
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public Float getSweptVolume() {
        return sweptVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto.swept_volume
     *
     * @param sweptVolume the value for auto.swept_volume
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setSweptVolume(Float sweptVolume) {
        this.sweptVolume = sweptVolume;
    }
}