package com.care.mybatis.bean;

public class AutoBrand {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_brand.id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_brand.name
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_brand.country_id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private Integer countryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_brand.year
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private String year;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_brand.pinyin
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private String pinyin;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_brand.id
	 * @return  the value of auto_brand.id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_brand.id
	 * @param id  the value for auto_brand.id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_brand.name
	 * @return  the value of auto_brand.name
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_brand.name
	 * @param name  the value for auto_brand.name
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_brand.country_id
	 * @return  the value of auto_brand.country_id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public Integer getCountryId() {
		return countryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_brand.country_id
	 * @param countryId  the value for auto_brand.country_id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_brand.year
	 * @return  the value of auto_brand.year
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public String getYear() {
		return year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_brand.year
	 * @param year  the value for auto_brand.year
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setYear(String year) {
		this.year = year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_brand.pinyin
	 * @return  the value of auto_brand.pinyin
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public String getPinyin() {
		return pinyin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_brand.pinyin
	 * @param pinyin  the value for auto_brand.pinyin
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setPinyin(String pinyin) {
		this.pinyin = pinyin;
	}
}