package com.care.mybatis.bean;

public class AutoWidgetAbs {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_abs.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_abs.name
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_abs.descr
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private String descr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_abs.widget_type
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private Integer widgetType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_abs.face
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private Boolean face;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_abs.hot
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private Boolean hot;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_abs.id
	 * @return  the value of auto_widget_abs.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_abs.id
	 * @param id  the value for auto_widget_abs.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_abs.name
	 * @return  the value of auto_widget_abs.name
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_abs.name
	 * @param name  the value for auto_widget_abs.name
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_abs.descr
	 * @return  the value of auto_widget_abs.descr
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public String getDescr() {
		return descr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_abs.descr
	 * @param descr  the value for auto_widget_abs.descr
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setDescr(String descr) {
		this.descr = descr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_abs.widget_type
	 * @return  the value of auto_widget_abs.widget_type
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public Integer getWidgetType() {
		return widgetType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_abs.widget_type
	 * @param widgetType  the value for auto_widget_abs.widget_type
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setWidgetType(Integer widgetType) {
		this.widgetType = widgetType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_abs.face
	 * @return  the value of auto_widget_abs.face
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public Boolean getFace() {
		return face;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_abs.face
	 * @param face  the value for auto_widget_abs.face
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setFace(Boolean face) {
		this.face = face;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_abs.hot
	 * @return  the value of auto_widget_abs.hot
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public Boolean getHot() {
		return hot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_abs.hot
	 * @param hot  the value for auto_widget_abs.hot
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setHot(Boolean hot) {
		this.hot = hot;
	}
}