package com.care.mybatis.bean;

import java.util.Date;

public class AutoYear {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_year.id
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_year.name
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_year.type_id
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	private Integer typeId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_year.id
	 * @return  the value of auto_year.id
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_year.id
	 * @param id  the value for auto_year.id
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_year.name
	 * @return  the value of auto_year.name
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_year.name
	 * @param name  the value for auto_year.name
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_year.type_id
	 * @return  the value of auto_year.type_id
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public Integer getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_year.type_id
	 * @param typeId  the value for auto_year.type_id
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}
}