package com.care.mybatis.bean;

public class AutoType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_type.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_type.name
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_type.brand_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer brandId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_type.id
     *
     * @return the value of auto_type.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_type.id
     *
     * @param id the value for auto_type.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_type.name
     *
     * @return the value of auto_type.name
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_type.name
     *
     * @param name the value for auto_type.name
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_type.brand_id
     *
     * @return the value of auto_type.brand_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_type.brand_id
     *
     * @param brandId the value for auto_type.brand_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }
}