package com.care.mybatis.bean;

public class AutoQuantity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_quantity.id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_quantity.name
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_quantity.id
     *
     * @return the value of auto_quantity.id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_quantity.id
     *
     * @param id the value for auto_quantity.id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_quantity.name
     *
     * @return the value of auto_quantity.name
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_quantity.name
     *
     * @param name the value for auto_quantity.name
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }
}