package com.care.mybatis.bean;

public class AutoWidgetType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.id
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.name
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.year_id
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	private Integer yearId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.id
	 * @return  the value of auto_widget_type.id
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.id
	 * @param id  the value for auto_widget_type.id
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.name
	 * @return  the value of auto_widget_type.name
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.name
	 * @param name  the value for auto_widget_type.name
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.year_id
	 * @return  the value of auto_widget_type.year_id
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	public Integer getYearId() {
		return yearId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.year_id
	 * @param yearId  the value for auto_widget_type.year_id
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	public void setYearId(Integer yearId) {
		this.yearId = yearId;
	}
}