package com.care.mybatis.bean;

public class AutoWidget {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_widget.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_widget.vendor_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer vendorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_widget.auto_type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer autoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_widget.type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_widget.abs_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer absId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_widget.user_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_widget.name
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_widget.no
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_widget.price
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_widget.img
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_widget.quantity
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_widget.descr
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private String descr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_widget.id
     *
     * @return the value of auto_widget.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_widget.id
     *
     * @param id the value for auto_widget.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_widget.vendor_id
     *
     * @return the value of auto_widget.vendor_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getVendorId() {
        return vendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_widget.vendor_id
     *
     * @param vendorId the value for auto_widget.vendor_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setVendorId(Integer vendorId) {
        this.vendorId = vendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_widget.auto_type
     *
     * @return the value of auto_widget.auto_type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getAutoType() {
        return autoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_widget.auto_type
     *
     * @param autoType the value for auto_widget.auto_type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setAutoType(Integer autoType) {
        this.autoType = autoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_widget.type
     *
     * @return the value of auto_widget.type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_widget.type
     *
     * @param type the value for auto_widget.type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_widget.abs_id
     *
     * @return the value of auto_widget.abs_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getAbsId() {
        return absId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_widget.abs_id
     *
     * @param absId the value for auto_widget.abs_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setAbsId(Integer absId) {
        this.absId = absId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_widget.user_id
     *
     * @return the value of auto_widget.user_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_widget.user_id
     *
     * @param userId the value for auto_widget.user_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_widget.name
     *
     * @return the value of auto_widget.name
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_widget.name
     *
     * @param name the value for auto_widget.name
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_widget.no
     *
     * @return the value of auto_widget.no
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_widget.no
     *
     * @param no the value for auto_widget.no
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_widget.price
     *
     * @return the value of auto_widget.price
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_widget.price
     *
     * @param price the value for auto_widget.price
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_widget.img
     *
     * @return the value of auto_widget.img
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_widget.img
     *
     * @param img the value for auto_widget.img
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_widget.quantity
     *
     * @return the value of auto_widget.quantity
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_widget.quantity
     *
     * @param quantity the value for auto_widget.quantity
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_widget.descr
     *
     * @return the value of auto_widget.descr
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_widget.descr
     *
     * @param descr the value for auto_widget.descr
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }
}