package com.care.mybatis.bean;

public class AutoWidgetType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.id
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.name
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.brand_id
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	private Integer brandId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.s_status
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	private Integer sStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.sort
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.hot
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	private Boolean hot;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.face
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	private Boolean face;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.autobrand_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	private Integer autobrandR;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.autotype_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	private Integer autotypeR;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.autovolume_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	private Integer autovolumeR;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget_type.autoyear_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	private Integer autoyearR;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.id
	 * @return  the value of auto_widget_type.id
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.id
	 * @param id  the value for auto_widget_type.id
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.name
	 * @return  the value of auto_widget_type.name
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.name
	 * @param name  the value for auto_widget_type.name
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.brand_id
	 * @return  the value of auto_widget_type.brand_id
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public Integer getBrandId() {
		return brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.brand_id
	 * @param brandId  the value for auto_widget_type.brand_id
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.s_status
	 * @return  the value of auto_widget_type.s_status
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public Integer getsStatus() {
		return sStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.s_status
	 * @param sStatus  the value for auto_widget_type.s_status
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void setsStatus(Integer sStatus) {
		this.sStatus = sStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.sort
	 * @return  the value of auto_widget_type.sort
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.sort
	 * @param sort  the value for auto_widget_type.sort
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.hot
	 * @return  the value of auto_widget_type.hot
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public Boolean getHot() {
		return hot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.hot
	 * @param hot  the value for auto_widget_type.hot
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void setHot(Boolean hot) {
		this.hot = hot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.face
	 * @return  the value of auto_widget_type.face
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public Boolean getFace() {
		return face;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.face
	 * @param face  the value for auto_widget_type.face
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void setFace(Boolean face) {
		this.face = face;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.autobrand_r
	 * @return  the value of auto_widget_type.autobrand_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public Integer getAutobrandR() {
		return autobrandR;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.autobrand_r
	 * @param autobrandR  the value for auto_widget_type.autobrand_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void setAutobrandR(Integer autobrandR) {
		this.autobrandR = autobrandR;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.autotype_r
	 * @return  the value of auto_widget_type.autotype_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public Integer getAutotypeR() {
		return autotypeR;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.autotype_r
	 * @param autotypeR  the value for auto_widget_type.autotype_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void setAutotypeR(Integer autotypeR) {
		this.autotypeR = autotypeR;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.autovolume_r
	 * @return  the value of auto_widget_type.autovolume_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public Integer getAutovolumeR() {
		return autovolumeR;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.autovolume_r
	 * @param autovolumeR  the value for auto_widget_type.autovolume_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void setAutovolumeR(Integer autovolumeR) {
		this.autovolumeR = autovolumeR;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget_type.autoyear_r
	 * @return  the value of auto_widget_type.autoyear_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public Integer getAutoyearR() {
		return autoyearR;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget_type.autoyear_r
	 * @param autoyearR  the value for auto_widget_type.autoyear_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void setAutoyearR(Integer autoyearR) {
		this.autoyearR = autoyearR;
	}
}