package com.care.mybatis.bean;

public class AutoWidget {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget.id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget.name
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget.price
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private Float price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget.user_id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget.type
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget.img
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private String img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget.link
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private String link;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget.auto_id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private Integer autoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget.quantity
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private Integer quantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget.hot
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private Boolean hot;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auto_widget.face
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	private Boolean face;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget.id
	 * @return  the value of auto_widget.id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget.id
	 * @param id  the value for auto_widget.id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget.name
	 * @return  the value of auto_widget.name
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget.name
	 * @param name  the value for auto_widget.name
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget.price
	 * @return  the value of auto_widget.price
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public Float getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget.price
	 * @param price  the value for auto_widget.price
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setPrice(Float price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget.user_id
	 * @return  the value of auto_widget.user_id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget.user_id
	 * @param userId  the value for auto_widget.user_id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget.type
	 * @return  the value of auto_widget.type
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget.type
	 * @param type  the value for auto_widget.type
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget.img
	 * @return  the value of auto_widget.img
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget.img
	 * @param img  the value for auto_widget.img
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setImg(String img) {
		this.img = img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget.link
	 * @return  the value of auto_widget.link
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public String getLink() {
		return link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget.link
	 * @param link  the value for auto_widget.link
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setLink(String link) {
		this.link = link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget.auto_id
	 * @return  the value of auto_widget.auto_id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public Integer getAutoId() {
		return autoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget.auto_id
	 * @param autoId  the value for auto_widget.auto_id
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setAutoId(Integer autoId) {
		this.autoId = autoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget.quantity
	 * @return  the value of auto_widget.quantity
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget.quantity
	 * @param quantity  the value for auto_widget.quantity
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget.hot
	 * @return  the value of auto_widget.hot
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public Boolean getHot() {
		return hot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget.hot
	 * @param hot  the value for auto_widget.hot
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setHot(Boolean hot) {
		this.hot = hot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auto_widget.face
	 * @return  the value of auto_widget.face
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public Boolean getFace() {
		return face;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auto_widget.face
	 * @param face  the value for auto_widget.face
	 * @mbggenerated  Sun May 11 23:10:41 CST 2014
	 */
	public void setFace(Boolean face) {
		this.face = face;
	}
}