package com.care.mybatis.bean;

public class AutoFault {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_fault.id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_fault.content
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_fault.img
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_fault.type
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_fault.id
     *
     * @return the value of auto_fault.id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_fault.id
     *
     * @param id the value for auto_fault.id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_fault.content
     *
     * @return the value of auto_fault.content
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_fault.content
     *
     * @param content the value for auto_fault.content
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_fault.img
     *
     * @return the value of auto_fault.img
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_fault.img
     *
     * @param img the value for auto_fault.img
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_fault.type
     *
     * @return the value of auto_fault.type
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_fault.type
     *
     * @param type the value for auto_fault.type
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setType(Integer type) {
        this.type = type;
    }
}