package com.care.mybatis.bean;

public class City {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column city.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column city.name
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column city.code
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private String code;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column city.id
	 * @return  the value of city.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column city.id
	 * @param id  the value for city.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column city.name
	 * @return  the value of city.name
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column city.name
	 * @param name  the value for city.name
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column city.code
	 * @return  the value of city.code
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column city.code
	 * @param code  the value for city.code
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setCode(String code) {
		this.code = code;
	}
}