package com.care.mybatis.bean;

public class Country {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column country.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column country.name
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column country.id
	 * @return  the value of country.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column country.id
	 * @param id  the value for country.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column country.name
	 * @return  the value of country.name
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column country.name
	 * @param name  the value for country.name
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}
}