package com.care.mybatis.bean;

public class OrderItem {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item.id
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item.o_id
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	private Integer oId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item.p_id
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	private Integer pId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item.p_quantity
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	private Integer pQuantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item.p_price
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	private Float pPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item.p_name
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	private String pName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item.id
	 * @return  the value of order_item.id
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item.id
	 * @param id  the value for order_item.id
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item.o_id
	 * @return  the value of order_item.o_id
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	public Integer getoId() {
		return oId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item.o_id
	 * @param oId  the value for order_item.o_id
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	public void setoId(Integer oId) {
		this.oId = oId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item.p_id
	 * @return  the value of order_item.p_id
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	public Integer getpId() {
		return pId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item.p_id
	 * @param pId  the value for order_item.p_id
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	public void setpId(Integer pId) {
		this.pId = pId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item.p_quantity
	 * @return  the value of order_item.p_quantity
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	public Integer getpQuantity() {
		return pQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item.p_quantity
	 * @param pQuantity  the value for order_item.p_quantity
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	public void setpQuantity(Integer pQuantity) {
		this.pQuantity = pQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item.p_price
	 * @return  the value of order_item.p_price
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	public Float getpPrice() {
		return pPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item.p_price
	 * @param pPrice  the value for order_item.p_price
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	public void setpPrice(Float pPrice) {
		this.pPrice = pPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item.p_name
	 * @return  the value of order_item.p_name
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	public String getpName() {
		return pName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item.p_name
	 * @param pName  the value for order_item.p_name
	 * @mbggenerated  Sun May 11 15:20:09 CST 2014
	 */
	public void setpName(String pName) {
		this.pName = pName;
	}
}