package com.care.mybatis.bean;

import java.util.Date;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.p_no
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private String pNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.c_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.time
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.total_price
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Float totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.status
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.invoice
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer invoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.addr_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer addrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ship_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer shipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ship_time
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Date shipTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.desc
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.invoice_name
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private String invoiceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.time1
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Date time1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.p_no
     *
     * @return the value of orders.p_no
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public String getpNo() {
        return pNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.p_no
     *
     * @param pNo the value for orders.p_no
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setpNo(String pNo) {
        this.pNo = pNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.c_id
     *
     * @return the value of orders.c_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.c_id
     *
     * @param cId the value for orders.c_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.time
     *
     * @return the value of orders.time
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.time
     *
     * @param time the value for orders.time
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.total_price
     *
     * @return the value of orders.total_price
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Float getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.total_price
     *
     * @param totalPrice the value for orders.total_price
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setTotalPrice(Float totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.status
     *
     * @return the value of orders.status
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.status
     *
     * @param status the value for orders.status
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_type
     *
     * @return the value of orders.pay_type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_type
     *
     * @param payType the value for orders.pay_type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.invoice
     *
     * @return the value of orders.invoice
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getInvoice() {
        return invoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.invoice
     *
     * @param invoice the value for orders.invoice
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setInvoice(Integer invoice) {
        this.invoice = invoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.addr_id
     *
     * @return the value of orders.addr_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getAddrId() {
        return addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.addr_id
     *
     * @param addrId the value for orders.addr_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setAddrId(Integer addrId) {
        this.addrId = addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ship_id
     *
     * @return the value of orders.ship_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getShipId() {
        return shipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ship_id
     *
     * @param shipId the value for orders.ship_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setShipId(Integer shipId) {
        this.shipId = shipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ship_time
     *
     * @return the value of orders.ship_time
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Date getShipTime() {
        return shipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ship_time
     *
     * @param shipTime the value for orders.ship_time
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setShipTime(Date shipTime) {
        this.shipTime = shipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.desc
     *
     * @return the value of orders.desc
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.desc
     *
     * @param desc the value for orders.desc
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.invoice_name
     *
     * @return the value of orders.invoice_name
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public String getInvoiceName() {
        return invoiceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.invoice_name
     *
     * @param invoiceName the value for orders.invoice_name
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setInvoiceName(String invoiceName) {
        this.invoiceName = invoiceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.time1
     *
     * @return the value of orders.time1
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Date getTime1() {
        return time1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.time1
     *
     * @param time1 the value for orders.time1
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setTime1(Date time1) {
        this.time1 = time1;
    }
}