package com.care.mybatis.bean;

import java.util.Date;

public class OrderNoSeqs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_no_seqs.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_no_seqs.date
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_no_seqs.user_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_no_seqs.id
     *
     * @return the value of order_no_seqs.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_no_seqs.id
     *
     * @param id the value for order_no_seqs.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_no_seqs.date
     *
     * @return the value of order_no_seqs.date
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_no_seqs.date
     *
     * @param date the value for order_no_seqs.date
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_no_seqs.user_id
     *
     * @return the value of order_no_seqs.user_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_no_seqs.user_id
     *
     * @param userId the value for order_no_seqs.user_id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}