package com.care.mybatis.bean;

public class UIAdver {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_adver.id
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_adver.link
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	private String link;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_adver.desc
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	private String desc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_adver.img
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	private String img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_adver.sort
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	private Integer sort;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_adver.id
	 * @return  the value of ui_adver.id
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_adver.id
	 * @param id  the value for ui_adver.id
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_adver.link
	 * @return  the value of ui_adver.link
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	public String getLink() {
		return link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_adver.link
	 * @param link  the value for ui_adver.link
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	public void setLink(String link) {
		this.link = link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_adver.desc
	 * @return  the value of ui_adver.desc
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_adver.desc
	 * @param desc  the value for ui_adver.desc
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_adver.img
	 * @return  the value of ui_adver.img
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_adver.img
	 * @param img  the value for ui_adver.img
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	public void setImg(String img) {
		this.img = img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_adver.sort
	 * @return  the value of ui_adver.sort
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_adver.sort
	 * @param sort  the value for ui_adver.sort
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}
}