package com.care.mybatis.bean;

public class UIKnowledge {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_knowledge.id
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_knowledge.desc
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	private String desc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_knowledge.id
	 * @return  the value of ui_knowledge.id
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_knowledge.id
	 * @param id  the value for ui_knowledge.id
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_knowledge.desc
	 * @return  the value of ui_knowledge.desc
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_knowledge.desc
	 * @param desc  the value for ui_knowledge.desc
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}
}