package com.care.mybatis.bean;

public class UILink {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_link.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_link.link
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private String link;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_link.desc
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private String desc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_link.id
	 * @return  the value of ui_link.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_link.id
	 * @param id  the value for ui_link.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_link.link
	 * @return  the value of ui_link.link
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public String getLink() {
		return link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_link.link
	 * @param link  the value for ui_link.link
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setLink(String link) {
		this.link = link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_link.desc
	 * @return  the value of ui_link.desc
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_link.desc
	 * @param desc  the value for ui_link.desc
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}
}