package com.care.mybatis.bean;

import java.util.Date;

public class UINews {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_news.id
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_news.title
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_news.author
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	private String author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_news.time
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_news.content
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_news.id
	 * @return  the value of ui_news.id
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_news.id
	 * @param id  the value for ui_news.id
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_news.title
	 * @return  the value of ui_news.title
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_news.title
	 * @param title  the value for ui_news.title
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_news.author
	 * @return  the value of ui_news.author
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_news.author
	 * @param author  the value for ui_news.author
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_news.time
	 * @return  the value of ui_news.time
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_news.time
	 * @param time  the value for ui_news.time
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_news.content
	 * @return  the value of ui_news.content
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_news.content
	 * @param content  the value for ui_news.content
	 * @mbggenerated  Mon May 12 22:38:15 CST 2014
	 */
	public void setContent(String content) {
		this.content = content;
	}
}