package com.care.mybatis.bean;

public class UIQuickSales {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_quick_sales.id
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	private Integer id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_quick_sales.id
	 * @return  the value of ui_quick_sales.id
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_quick_sales.id
	 * @param id  the value for ui_quick_sales.id
	 * @mbggenerated  Sun May 11 14:15:21 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}
}