package com.care.mybatis.bean;

public class UIVideo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_video.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_video.desc
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_video.link
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_video.sort
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_video.id
     *
     * @return the value of ui_video.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_video.id
     *
     * @param id the value for ui_video.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_video.desc
     *
     * @return the value of ui_video.desc
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_video.desc
     *
     * @param desc the value for ui_video.desc
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_video.link
     *
     * @return the value of ui_video.link
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_video.link
     *
     * @param link the value for ui_video.link
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_video.sort
     *
     * @return the value of ui_video.sort
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_video.sort
     *
     * @param sort the value for ui_video.sort
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}