package com.care.mybatis.bean;

public class UIWebDesc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_web_desc.id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_web_desc.content
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_web_desc.id
     *
     * @return the value of ui_web_desc.id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_web_desc.id
     *
     * @param id the value for ui_web_desc.id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_web_desc.content
     *
     * @return the value of ui_web_desc.content
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_web_desc.content
     *
     * @param content the value for ui_web_desc.content
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }
}