package com.care.mybatis.bean;

public class UserStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_status.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_status.name
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_status.level
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_status.id
     *
     * @return the value of user_status.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_status.id
     *
     * @param id the value for user_status.id
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_status.name
     *
     * @return the value of user_status.name
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_status.name
     *
     * @param name the value for user_status.name
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_status.level
     *
     * @return the value of user_status.level
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_status.level
     *
     * @param level the value for user_status.level
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}