package com.care.mybatis.bean;

public class UserAddress {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_address.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_address.address
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_address.phone
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_address.user_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_address.post_no
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private String postNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_address.user_name
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_address.is_default
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private Integer isDefault;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_address.id
	 * @return  the value of user_address.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_address.id
	 * @param id  the value for user_address.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_address.address
	 * @return  the value of user_address.address
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_address.address
	 * @param address  the value for user_address.address
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_address.phone
	 * @return  the value of user_address.phone
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_address.phone
	 * @param phone  the value for user_address.phone
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_address.user_id
	 * @return  the value of user_address.user_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_address.user_id
	 * @param userId  the value for user_address.user_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_address.post_no
	 * @return  the value of user_address.post_no
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public String getPostNo() {
		return postNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_address.post_no
	 * @param postNo  the value for user_address.post_no
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setPostNo(String postNo) {
		this.postNo = postNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_address.user_name
	 * @return  the value of user_address.user_name
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_address.user_name
	 * @param userName  the value for user_address.user_name
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_address.is_default
	 * @return  the value of user_address.is_default
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public Integer getIsDefault() {
		return isDefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_address.is_default
	 * @param isDefault  the value for user_address.is_default
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setIsDefault(Integer isDefault) {
		this.isDefault = isDefault;
	}

}
    