package com.care.mybatis.bean;

public class UserOperate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate.id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate.name
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate.group
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    private Integer group;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate.id
     *
     * @return the value of user_operate.id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate.id
     *
     * @param id the value for user_operate.id
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate.name
     *
     * @return the value of user_operate.name
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate.name
     *
     * @param name the value for user_operate.name
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate.group
     *
     * @return the value of user_operate.group
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public Integer getGroup() {
        return group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate.group
     *
     * @param group the value for user_operate.group
     *
     * @mbggenerated Sat May 03 15:51:52 CST 2014
     */
    public void setGroup(Integer group) {
        this.group = group;
    }
}