package com.care.mybatis.bean;

public class UserOperateGroup {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_operate_group.id
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_operate_group.name
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_operate_group.id
	 * @return  the value of user_operate_group.id
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_operate_group.id
	 * @param id  the value for user_operate_group.id
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_operate_group.name
	 * @return  the value of user_operate_group.name
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_operate_group.name
	 * @param name  the value for user_operate_group.name
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}
}