package com.care.mybatis.bean;

public class UserFavorite {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_favorite.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_favorite.u_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private Integer uId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_favorite.p_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private Integer pId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_favorite.id
	 * @return  the value of user_favorite.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_favorite.id
	 * @param id  the value for user_favorite.id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_favorite.u_id
	 * @return  the value of user_favorite.u_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public Integer getuId() {
		return uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_favorite.u_id
	 * @param uId  the value for user_favorite.u_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setuId(Integer uId) {
		this.uId = uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_favorite.p_id
	 * @return  the value of user_favorite.p_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public Integer getpId() {
		return pId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_favorite.p_id
	 * @param pId  the value for user_favorite.p_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setpId(Integer pId) {
		this.pId = pId;
	}
}