package com.care.mybatis.bean;

public class widgettype_autovolume_r {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column widgettype_autovolume_r.widget_type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer widgetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column widgettype_autovolume_r.volume
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    private Integer volume;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column widgettype_autovolume_r.widget_type
     *
     * @return the value of widgettype_autovolume_r.widget_type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getWidgetType() {
        return widgetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column widgettype_autovolume_r.widget_type
     *
     * @param widgetType the value for widgettype_autovolume_r.widget_type
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setWidgetType(Integer widgetType) {
        this.widgetType = widgetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column widgettype_autovolume_r.volume
     *
     * @return the value of widgettype_autovolume_r.volume
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public Integer getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column widgettype_autovolume_r.volume
     *
     * @param volume the value for widgettype_autovolume_r.volume
     *
     * @mbggenerated Mon May 19 22:20:36 CST 2014
     */
    public void setVolume(Integer volume) {
        this.volume = volume;
    }
}