package com.care.mybatis.bean;

public class widgettype_autoyear_r {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column widgettype_autoyear_r.widget_type
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	private Integer widgetType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column widgettype_autoyear_r.year
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	private Integer year;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column widgettype_autoyear_r.widget_type
	 * @return  the value of widgettype_autoyear_r.widget_type
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public Integer getWidgetType() {
		return widgetType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column widgettype_autoyear_r.widget_type
	 * @param widgetType  the value for widgettype_autoyear_r.widget_type
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void setWidgetType(Integer widgetType) {
		this.widgetType = widgetType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column widgettype_autoyear_r.year
	 * @return  the value of widgettype_autoyear_r.year
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public Integer getYear() {
		return year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column widgettype_autoyear_r.year
	 * @param year  the value for widgettype_autoyear_r.year
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void setYear(Integer year) {
		this.year = year;
	}
}