package com.care.mybatis.bean;

public class widgettype_autotype_r {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column widgettype_autotype_r.widget_type
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private Integer widgetType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column widgettype_autotype_r.auto_type
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private Integer autoType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column widgettype_autotype_r.widget_type
	 * @return  the value of widgettype_autotype_r.widget_type
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public Integer getWidgetType() {
		return widgetType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column widgettype_autotype_r.widget_type
	 * @param widgetType  the value for widgettype_autotype_r.widget_type
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setWidgetType(Integer widgetType) {
		this.widgetType = widgetType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column widgettype_autotype_r.auto_type
	 * @return  the value of widgettype_autotype_r.auto_type
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public Integer getAutoType() {
		return autoType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column widgettype_autotype_r.auto_type
	 * @param autoType  the value for widgettype_autotype_r.auto_type
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setAutoType(Integer autoType) {
		this.autoType = autoType;
	}
}