package com.care.mybatis.bean;

public class widgettype_autobrand_r {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column widgettype_autobrand_r.widget_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private Integer widgetId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column widgettype_autobrand_r.brand_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	private Integer brandId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column widgettype_autobrand_r.widget_id
	 * @return  the value of widgettype_autobrand_r.widget_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public Integer getWidgetId() {
		return widgetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column widgettype_autobrand_r.widget_id
	 * @param widgetId  the value for widgettype_autobrand_r.widget_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setWidgetId(Integer widgetId) {
		this.widgetId = widgetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column widgettype_autobrand_r.brand_id
	 * @return  the value of widgettype_autobrand_r.brand_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public Integer getBrandId() {
		return brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column widgettype_autobrand_r.brand_id
	 * @param brandId  the value for widgettype_autobrand_r.brand_id
	 * @mbggenerated  Sat May 17 18:59:17 CST 2014
	 */
	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}
}