package com.care.mybatis.bean;

import java.util.ArrayList;
import java.util.List;

public class widgettype_autovolume_rExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table widgettype_autovolume_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table widgettype_autovolume_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table widgettype_autovolume_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autovolume_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public widgettype_autovolume_rExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autovolume_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autovolume_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autovolume_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autovolume_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autovolume_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autovolume_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autovolume_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autovolume_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autovolume_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table widgettype_autovolume_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table widgettype_autovolume_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andWidgetTypeIsNull() {
			addCriterion("widget_type is null");
			return (Criteria) this;
		}

		public Criteria andWidgetTypeIsNotNull() {
			addCriterion("widget_type is not null");
			return (Criteria) this;
		}

		public Criteria andWidgetTypeEqualTo(Integer value) {
			addCriterion("widget_type =", value, "widgetType");
			return (Criteria) this;
		}

		public Criteria andWidgetTypeNotEqualTo(Integer value) {
			addCriterion("widget_type <>", value, "widgetType");
			return (Criteria) this;
		}

		public Criteria andWidgetTypeGreaterThan(Integer value) {
			addCriterion("widget_type >", value, "widgetType");
			return (Criteria) this;
		}

		public Criteria andWidgetTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("widget_type >=", value, "widgetType");
			return (Criteria) this;
		}

		public Criteria andWidgetTypeLessThan(Integer value) {
			addCriterion("widget_type <", value, "widgetType");
			return (Criteria) this;
		}

		public Criteria andWidgetTypeLessThanOrEqualTo(Integer value) {
			addCriterion("widget_type <=", value, "widgetType");
			return (Criteria) this;
		}

		public Criteria andWidgetTypeIn(List<Integer> values) {
			addCriterion("widget_type in", values, "widgetType");
			return (Criteria) this;
		}

		public Criteria andWidgetTypeNotIn(List<Integer> values) {
			addCriterion("widget_type not in", values, "widgetType");
			return (Criteria) this;
		}

		public Criteria andWidgetTypeBetween(Integer value1, Integer value2) {
			addCriterion("widget_type between", value1, value2, "widgetType");
			return (Criteria) this;
		}

		public Criteria andWidgetTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("widget_type not between", value1, value2,
					"widgetType");
			return (Criteria) this;
		}

		public Criteria andVolumeIsNull() {
			addCriterion("volume is null");
			return (Criteria) this;
		}

		public Criteria andVolumeIsNotNull() {
			addCriterion("volume is not null");
			return (Criteria) this;
		}

		public Criteria andVolumeEqualTo(Integer value) {
			addCriterion("volume =", value, "volume");
			return (Criteria) this;
		}

		public Criteria andVolumeNotEqualTo(Integer value) {
			addCriterion("volume <>", value, "volume");
			return (Criteria) this;
		}

		public Criteria andVolumeGreaterThan(Integer value) {
			addCriterion("volume >", value, "volume");
			return (Criteria) this;
		}

		public Criteria andVolumeGreaterThanOrEqualTo(Integer value) {
			addCriterion("volume >=", value, "volume");
			return (Criteria) this;
		}

		public Criteria andVolumeLessThan(Integer value) {
			addCriterion("volume <", value, "volume");
			return (Criteria) this;
		}

		public Criteria andVolumeLessThanOrEqualTo(Integer value) {
			addCriterion("volume <=", value, "volume");
			return (Criteria) this;
		}

		public Criteria andVolumeIn(List<Integer> values) {
			addCriterion("volume in", values, "volume");
			return (Criteria) this;
		}

		public Criteria andVolumeNotIn(List<Integer> values) {
			addCriterion("volume not in", values, "volume");
			return (Criteria) this;
		}

		public Criteria andVolumeBetween(Integer value1, Integer value2) {
			addCriterion("volume between", value1, value2, "volume");
			return (Criteria) this;
		}

		public Criteria andVolumeNotBetween(Integer value1, Integer value2) {
			addCriterion("volume not between", value1, value2, "volume");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table widgettype_autovolume_r
	 * @mbggenerated  Wed May 14 23:52:52 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table widgettype_autovolume_r
     *
     * @mbggenerated do_not_delete_during_merge Wed May 14 23:50:08 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}